language: ruby
dist: focal
rvm:
  - 3.3.5

cache:
  bundler: true

addons:
  apt:
    packages:
      - cmake
      - libcurl4-openssl-dev

before_install:
  - gem update --system 3.5.8
  - gem install bundler -v 2.5.8
  - bundle config set deployment true
  - bundle config set path 'vendor/bundle'
  - bundle config set force_ruby_platform true
  - bundler -v
  - gem -v

install:
  - bundle install --jobs=3 --retry=3

before_script:
  - chmod +x ./script/*

script:
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then echo -e "# cibuildindex via cron"; fi
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then travis_wait 35 ./script/cibuildindex; fi
  - if [ "$TRAVIS_EVENT_TYPE" = "api" ]; then echo -e "# cibuild via api"; fi
  - if [ "$TRAVIS_EVENT_TYPE" = "api" ]; then travis_wait 35 ./script/cibuild; fi
  - if [ "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then echo -e "# cibuild via pull_request"; fi
  - if [ "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then travis_wait 35 ./script/cibuild; fi
  - if [ "$TRAVIS_EVENT_TYPE" = "push" ]; then echo -e "# cibuild via push"; fi
  - if [ "$TRAVIS_EVENT_TYPE" = "push" ]; then travis_wait 35 ./script/cibuild; fi

branches:
  only:
    - master

deploy:
  provider: s3
  access_key_id:
    secure: obmIm6pUTccxYBZ+...
  secret_access_key:
    secure: uDEDck8YRB2lrrpdkZ+...
  bucket: whatthefuckjusthappenedtoday.com
  local_dir: _site
  skip_cleanup: true
  on:
    repo: mkiser/WTFJHT

after_deploy: >
  curl -X DELETE "https://api.cloudflare.com/client/v4/zones/2fa02b93146397fbf2001d812ab8b31f/purge_cache"
  -H "X-Auth-Email: $CLOUD_FLARE_EMAIL"
  -H "X-Auth-Key: $CLOUD_FLARE_API_KEY"
  -H "Content-Type: application/json"
  --data '{"purge_everything":true}'

notifications:
  slack:
    rooms:
      secure: oh1suThkyoPLUxMFWaNPtlIMICvJLztnibJGw75FzMDHV6m2cqho51k2kF97jMoQ6...
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) by %{author} %{result} in %{duration}"
  email:
    recipients:
      - matt@whatthefuckjusthappenedtoday.com
    on_success: never
    on_failure: always
  webhooks:
    - https://www.google.com/webmasters/tools/ping?sitemap=https://whatthefuckjusthappenedtoday.com/sitemap.xml
    - http://www.bing.com/ping?sitemap=https://whatthefuckjusthappenedtoday.com/sitemap.xml
